routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::resource('alumnos', 'AlumnoController');

Route::resource('catedraticos', 'CatedraticoController');
Route::resource('contratos', 'ContratoController');
Route::resource('grados', 'GradoController');
Route::resource('inscripcions', 'InscripcionController');
Route::resource('notas', 'NotaController');
Route::resource('seccions', 'SeccionController');
Route::resource('sucursals', 'SucursalController');

app/Http/Controllers/API/GradoController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use App\Http\Requests\GradoPostRequest;
use App\Http\Controllers\Controller;
use App\Http\Models\Grado\Grado;

class GradoController extends Controller
{


    public function index()
    {
        return Grado::all();
    }

    public function show(Request $request, Grado $grado)
    {
        return $grado;
    }

    public function store(GradoPostRequest $request)
    {
        $data = $request->validated();
        $grado = Grado::create($data);
        return $grado;
    }

    public function update(GradoPostRequest $request, Grado $grado)
    {
        $data = $request->validated();
        $grado->fill($data);
        $grado->save();

        return $grado;
    }

    public function destroy(Request $request, Grado $grado)
    {
        $grado->delete();
        return $grado;
    }

}

app/Http/Controllers/GradoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\GradoPostRequest;
use App\Http\Models\Grado\Grado;


class GradoController extends Controller
{

    public function index()
    {
        $grados = Grado::all();
        return view('grados.index', compact('grados'));
    }

    public function show(Request $request, Grado $grado)
    {
        return view('grados.show', compact('grado'));
    }

    public function create()
    {
        return view('grados.create');
    }

    public function store(GradoPostRequest $request)
    {
        $data = $request->validated();
        $grado = Grado::create($data);
        return redirect()->route('grados.index')->with('status', 'Grado created!');
    }

    public function edit(Request $request, Grado $grado)
    {
        return view('grados.edit', compact('grado'));
    }

    public function update(GradoPostRequest $request, Grado $grado)
    {
        $data = $request->validated();
        $grado->fill($data);
        $grado->save();
        return redirect()->route('grados.index')->with('status', 'Grado updated!');
    }

    public function destroy(Request $request, Grado $grado)
    {
        $grado->delete();
        return redirect()->route('grados.index')->with('status', 'Grado destroyed!');
    }
}

resources/views/grados/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="card">

        <div class="card-header">
            <h1> Grado Create </h1>
        </div>
        <div class="card-body">

        @if($errors->any())
        <ul>
            @foreach($errors->all() as $error)
            <li class="text-danger">{{ $error }}</li>
            @endforeach
        </ul @endif <form action="{{route('grados.store')}}" method="POST" novalidate>
        @csrf
        
                        <div class="form-group">
            <label for="id_grado">Id Grado</label>
                        <input class="form-control Integer"  type="number"  name="id_grado" id="id_grado" value="{{old('id_grado')}}"                         required="required"
                        >
                        @if($errors->has('id_grado'))
            <p class="text-danger">{{$errors->first('id_grado')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="nombre_grado">Nombre Grado</label>
                        <input class="form-control String"  type="text"  name="nombre_grado" id="nombre_grado" value="{{old('nombre_grado')}}"             maxlength="45"
                                    required="required"
                        >
                        @if($errors->has('nombre_grado'))
            <p class="text-danger">{{$errors->first('nombre_grado')}}</p>
            @endif
        </div>
                        <div>
            <button class="btn btn-primary" type="submit">Create</button>
            <a href="{{ url()->previous() }}">Back</a>
        </div>
        </form>
        </div>
    </div>
</div>
@endsection

resources/views/grados/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="card">

        <div class="card-header">
            <h1> Grado Edit </h1>
        </div>
        <div class="card-body">

    @if($errors->any())
    <ul>
        @foreach($errors->all() as $error)
        <li class="text-danger">{{ $error }}</li>
        @endforeach
    </ul>

    @endif

    <form action="{{route('grados.update',['grado'=>$grado->id])}}" method="POST" novalidate>
        @csrf
        @method('PUT')
        

                        <div class="form-group">
            <label for="id_grado">Id Grado</label>
                    <input class="form-control Integer"  type="number"  name="id_grado" id="id_grado" value="{{old('id_grado',$grado->id_grado)}}"
                                    required="required"
                        >
                    @if($errors->has('id_grado'))
            <p class="text-danger">{{$errors->first('id_grado')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="nombre_grado">Nombre Grado</label>
                    <input class="form-control String"  type="text"  name="nombre_grado" id="nombre_grado" value="{{old('nombre_grado',$grado->nombre_grado)}}"
                                    required="required"
                        >
                    @if($errors->has('nombre_grado'))
            <p class="text-danger">{{$errors->first('nombre_grado')}}</p>
            @endif
        </div>
                        <div>
            <button class="btn btn-primary" type="submit">Save</button>
            <a href="{{ url()->previous() }}">Back</a>
        </div>
    </form>
    </div>
        </div>

</div>
@endsection

resources/views/grados/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">

    @if(session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
    @endif
    <div class="card">
        <div class="card-header">
            <h1> Grados </h1>
        </div>
    <div class="card-body">

    <div>
        <a href="{{route('grados.create')}}">New</a>
    </div>
    <table class="table table-striped">
        @if(count($grados))
        <thead>
            <tr>
                <th>&nbsp;</th>
                                                <td>Id Grado</td>
                
                                                <td>Nombre Grado</td>
                
                            </tr>

        </thead>
        @endif
        <tbody>
            @forelse($grados as $grado)
            <tr>
                <td>
                    <a href="{{route('grados.show',['grado'=>$grado] )}}">Show</a>
                    <a href="{{route('grados.edit',['grado'=>$grado] )}}">Edit</a>
                    <a href="javascript:void(0)" onclick="event.preventDefault();
                    document.getElementById('delete-grado-{{$grado->id}}').submit();">
                        Delete
                    </a>
                    <form id="delete-grado-{{$grado->id}}" action="{{route('grados.destroy',['grado'=>$grado])}}" method="POST" style="display: none;">
                        @csrf
                        @method('DELETE')
                    </form>
                </td>
                                                <td>{{$grado->id_grado}}</td>
                                                                <td>{{$grado->nombre_grado}}</td>
                                
            </tr>
            @empty
            <p>No Grados</p>
            @endforelse
        </tbody>
    </table>
    </div>
    </div>

</div>

@endsection

resources/views/grados/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">

    <div class="card mb-4">

        <div class="card-header">
            <h1> Grado Show </h1>
        </div>

    <div class="card-body">
                        <div class="form-group">
            <label class="col-form-label" for="value">Id Grado</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$grado->id_grado}}">
        </div>
                                <div class="form-group">
            <label class="col-form-label" for="value">Nombre Grado</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$grado->nombre_grado}}">
        </div>
                    </div>

    </div>

    <div class="card mb-4">

        
    </div>



    <a href="{{ url()->previous() }}">Back</a>
</div>
@endsection