routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::resource('alumnos', 'AlumnoController');

Route::resource('catedraticos', 'CatedraticoController');
Route::resource('contratos', 'ContratoController');
Route::resource('grados', 'GradoController');
Route::resource('inscripcions', 'InscripcionController');
Route::resource('notas', 'NotaController');
Route::resource('seccions', 'SeccionController');
Route::resource('sucursals', 'SucursalController');

app/Http/Controllers/API/ContratoController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use App\Http\Requests\ContratoPostRequest;
use App\Http\Controllers\Controller;
use App\Http\Models\Contrato\Contrato;

class ContratoController extends Controller
{


    public function index()
    {
        return Contrato::all();
    }

    public function show(Request $request, Contrato $contrato)
    {
        return $contrato;
    }

    public function store(ContratoPostRequest $request)
    {
        $data = $request->validated();
        $contrato = Contrato::create($data);
        return $contrato;
    }

    public function update(ContratoPostRequest $request, Contrato $contrato)
    {
        $data = $request->validated();
        $contrato->fill($data);
        $contrato->save();

        return $contrato;
    }

    public function destroy(Request $request, Contrato $contrato)
    {
        $contrato->delete();
        return $contrato;
    }

}

app/Http/Controllers/ContratoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\ContratoPostRequest;
use App\Http\Models\Contrato\Contrato;


class ContratoController extends Controller
{

    public function index()
    {
        $contratos = Contrato::all();
        return view('contratos.index', compact('contratos'));
    }

    public function show(Request $request, Contrato $contrato)
    {
        return view('contratos.show', compact('contrato'));
    }

    public function create()
    {
        return view('contratos.create');
    }

    public function store(ContratoPostRequest $request)
    {
        $data = $request->validated();
        $contrato = Contrato::create($data);
        return redirect()->route('contratos.index')->with('status', 'Contrato created!');
    }

    public function edit(Request $request, Contrato $contrato)
    {
        return view('contratos.edit', compact('contrato'));
    }

    public function update(ContratoPostRequest $request, Contrato $contrato)
    {
        $data = $request->validated();
        $contrato->fill($data);
        $contrato->save();
        return redirect()->route('contratos.index')->with('status', 'Contrato updated!');
    }

    public function destroy(Request $request, Contrato $contrato)
    {
        $contrato->delete();
        return redirect()->route('contratos.index')->with('status', 'Contrato destroyed!');
    }
}

resources/views/contratos/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="card">

        <div class="card-header">
            <h1> Contrato Create </h1>
        </div>
        <div class="card-body">

        @if($errors->any())
        <ul>
            @foreach($errors->all() as $error)
            <li class="text-danger">{{ $error }}</li>
            @endforeach
        </ul @endif <form action="{{route('contratos.store')}}" method="POST" novalidate>
        @csrf
        
                        <div class="form-group">
            <label for="id_contrato">Id Contrato</label>
                        <input class="form-control Integer"  type="number"  name="id_contrato" id="id_contrato" value="{{old('id_contrato')}}"                         required="required"
                        >
                        @if($errors->has('id_contrato'))
            <p class="text-danger">{{$errors->first('id_contrato')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="seccion_id_seccion">Seccion Id Seccion</label>
                        <input class="form-control Integer"  type="number"  name="seccion_id_seccion" id="seccion_id_seccion" value="{{old('seccion_id_seccion')}}"                         required="required"
                        >
                        @if($errors->has('seccion_id_seccion'))
            <p class="text-danger">{{$errors->first('seccion_id_seccion')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="catedratico_id_catedratico">Catedratico Id Catedratico</label>
                        <input class="form-control Integer"  type="number"  name="catedratico_id_catedratico" id="catedratico_id_catedratico" value="{{old('catedratico_id_catedratico')}}"                         required="required"
                        >
                        @if($errors->has('catedratico_id_catedratico'))
            <p class="text-danger">{{$errors->first('catedratico_id_catedratico')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="fecha">Fecha</label>
                        <input class="form-control Date"  type="date"  name="fecha" id="fecha" value="{{old('fecha')}}"                         required="required"
                        >
                        @if($errors->has('fecha'))
            <p class="text-danger">{{$errors->first('fecha')}}</p>
            @endif
        </div>
                        <div>
            <button class="btn btn-primary" type="submit">Create</button>
            <a href="{{ url()->previous() }}">Back</a>
        </div>
        </form>
        </div>
    </div>
</div>
@endsection

resources/views/contratos/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="card">

        <div class="card-header">
            <h1> Contrato Edit </h1>
        </div>
        <div class="card-body">

    @if($errors->any())
    <ul>
        @foreach($errors->all() as $error)
        <li class="text-danger">{{ $error }}</li>
        @endforeach
    </ul>

    @endif

    <form action="{{route('contratos.update',['contrato'=>$contrato->id])}}" method="POST" novalidate>
        @csrf
        @method('PUT')
        

                        <div class="form-group">
            <label for="id_contrato">Id Contrato</label>
                    <input class="form-control Integer"  type="number"  name="id_contrato" id="id_contrato" value="{{old('id_contrato',$contrato->id_contrato)}}"
                                    required="required"
                        >
                    @if($errors->has('id_contrato'))
            <p class="text-danger">{{$errors->first('id_contrato')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="seccion_id_seccion">Seccion Id Seccion</label>
                    <input class="form-control Integer"  type="number"  name="seccion_id_seccion" id="seccion_id_seccion" value="{{old('seccion_id_seccion',$contrato->seccion_id_seccion)}}"
                                    required="required"
                        >
                    @if($errors->has('seccion_id_seccion'))
            <p class="text-danger">{{$errors->first('seccion_id_seccion')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="catedratico_id_catedratico">Catedratico Id Catedratico</label>
                    <input class="form-control Integer"  type="number"  name="catedratico_id_catedratico" id="catedratico_id_catedratico" value="{{old('catedratico_id_catedratico',$contrato->catedratico_id_catedratico)}}"
                                    required="required"
                        >
                    @if($errors->has('catedratico_id_catedratico'))
            <p class="text-danger">{{$errors->first('catedratico_id_catedratico')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="fecha">Fecha</label>
                    <input class="form-control Date"  type="date"  name="fecha" id="fecha" value="{{old('fecha',$contrato->fecha)}}"
                                    required="required"
                        >
                    @if($errors->has('fecha'))
            <p class="text-danger">{{$errors->first('fecha')}}</p>
            @endif
        </div>
                        <div>
            <button class="btn btn-primary" type="submit">Save</button>
            <a href="{{ url()->previous() }}">Back</a>
        </div>
    </form>
    </div>
        </div>

</div>
@endsection

resources/views/contratos/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">

    @if(session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
    @endif
    <div class="card">
        <div class="card-header">
            <h1> Contratos </h1>
        </div>
    <div class="card-body">

    <div>
        <a href="{{route('contratos.create')}}">New</a>
    </div>
    <table class="table table-striped">
        @if(count($contratos))
        <thead>
            <tr>
                <th>&nbsp;</th>
                                                <td>Id Contrato</td>
                
                                                <td>Seccion Id Seccion</td>
                
                                                <td>Catedratico Id Catedratico</td>
                
                                                <td>Fecha</td>
                
                            </tr>

        </thead>
        @endif
        <tbody>
            @forelse($contratos as $contrato)
            <tr>
                <td>
                    <a href="{{route('contratos.show',['contrato'=>$contrato] )}}">Show</a>
                    <a href="{{route('contratos.edit',['contrato'=>$contrato] )}}">Edit</a>
                    <a href="javascript:void(0)" onclick="event.preventDefault();
                    document.getElementById('delete-contrato-{{$contrato->id}}').submit();">
                        Delete
                    </a>
                    <form id="delete-contrato-{{$contrato->id}}" action="{{route('contratos.destroy',['contrato'=>$contrato])}}" method="POST" style="display: none;">
                        @csrf
                        @method('DELETE')
                    </form>
                </td>
                                                <td>{{$contrato->id_contrato}}</td>
                                                                <td>{{$contrato->seccion_id_seccion}}</td>
                                                                <td>{{$contrato->catedratico_id_catedratico}}</td>
                                                                <td>{{$contrato->fecha}}</td>
                                
            </tr>
            @empty
            <p>No Contratos</p>
            @endforelse
        </tbody>
    </table>
    </div>
    </div>

</div>

@endsection

resources/views/contratos/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">

    <div class="card mb-4">

        <div class="card-header">
            <h1> Contrato Show </h1>
        </div>

    <div class="card-body">
                        <div class="form-group">
            <label class="col-form-label" for="value">Id Contrato</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$contrato->id_contrato}}">
        </div>
                                <div class="form-group">
            <label class="col-form-label" for="value">Seccion Id Seccion</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$contrato->seccion_id_seccion}}">
        </div>
                                <div class="form-group">
            <label class="col-form-label" for="value">Catedratico Id Catedratico</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$contrato->catedratico_id_catedratico}}">
        </div>
                                <div class="form-group">
            <label class="col-form-label" for="value">Fecha</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$contrato->fecha}}">
        </div>
                    </div>

    </div>

    <div class="card mb-4">

        
    </div>



    <a href="{{ url()->previous() }}">Back</a>
</div>
@endsection