routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::resource('alumnos', 'AlumnoController');

Route::resource('catedraticos', 'CatedraticoController');
Route::resource('contratos', 'ContratoController');
Route::resource('grados', 'GradoController');
Route::resource('inscripcions', 'InscripcionController');
Route::resource('notas', 'NotaController');
Route::resource('seccions', 'SeccionController');
Route::resource('sucursals', 'SucursalController');

app/Http/Controllers/API/InscripcionController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use App\Http\Requests\InscripcionPostRequest;
use App\Http\Controllers\Controller;
use App\Http\Models\Inscripcion\Inscripcion;

class InscripcionController extends Controller
{


    public function index()
    {
        return Inscripcion::all();
    }

    public function show(Request $request, Inscripcion $inscripcion)
    {
        return $inscripcion;
    }

    public function store(InscripcionPostRequest $request)
    {
        $data = $request->validated();
        $inscripcion = Inscripcion::create($data);
        return $inscripcion;
    }

    public function update(InscripcionPostRequest $request, Inscripcion $inscripcion)
    {
        $data = $request->validated();
        $inscripcion->fill($data);
        $inscripcion->save();

        return $inscripcion;
    }

    public function destroy(Request $request, Inscripcion $inscripcion)
    {
        $inscripcion->delete();
        return $inscripcion;
    }

}

app/Http/Controllers/InscripcionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\InscripcionPostRequest;
use App\Http\Models\Inscripcion\Inscripcion;


class InscripcionController extends Controller
{

    public function index()
    {
        $inscripcions = Inscripcion::all();
        return view('inscripcions.index', compact('inscripcions'));
    }

    public function show(Request $request, Inscripcion $inscripcion)
    {
        return view('inscripcions.show', compact('inscripcion'));
    }

    public function create()
    {
        return view('inscripcions.create');
    }

    public function store(InscripcionPostRequest $request)
    {
        $data = $request->validated();
        $inscripcion = Inscripcion::create($data);
        return redirect()->route('inscripcions.index')->with('status', 'Inscripcion created!');
    }

    public function edit(Request $request, Inscripcion $inscripcion)
    {
        return view('inscripcions.edit', compact('inscripcion'));
    }

    public function update(InscripcionPostRequest $request, Inscripcion $inscripcion)
    {
        $data = $request->validated();
        $inscripcion->fill($data);
        $inscripcion->save();
        return redirect()->route('inscripcions.index')->with('status', 'Inscripcion updated!');
    }

    public function destroy(Request $request, Inscripcion $inscripcion)
    {
        $inscripcion->delete();
        return redirect()->route('inscripcions.index')->with('status', 'Inscripcion destroyed!');
    }
}

resources/views/inscripcions/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="card">

        <div class="card-header">
            <h1> Inscripcion Create </h1>
        </div>
        <div class="card-body">

        @if($errors->any())
        <ul>
            @foreach($errors->all() as $error)
            <li class="text-danger">{{ $error }}</li>
            @endforeach
        </ul @endif <form action="{{route('inscripcions.store')}}" method="POST" novalidate>
        @csrf
        
                        <div class="form-group">
            <label for="id_inscripcion">Id Inscripcion</label>
                        <input class="form-control Integer"  type="number"  name="id_inscripcion" id="id_inscripcion" value="{{old('id_inscripcion')}}"                         required="required"
                        >
                        @if($errors->has('id_inscripcion'))
            <p class="text-danger">{{$errors->first('id_inscripcion')}}</p>
            @endif
        </div>
                                                <div class="form-group">
            <label for="alumno_id_alumno">Alumno Id Alumno</label>
                        <input class="form-control Integer"  type="number"  name="alumno_id_alumno" id="alumno_id_alumno" value="{{old('alumno_id_alumno')}}"                         required="required"
                        >
                        @if($errors->has('alumno_id_alumno'))
            <p class="text-danger">{{$errors->first('alumno_id_alumno')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="seccion_id_seccion">Seccion Id Seccion</label>
                        <input class="form-control Integer"  type="number"  name="seccion_id_seccion" id="seccion_id_seccion" value="{{old('seccion_id_seccion')}}"                         required="required"
                        >
                        @if($errors->has('seccion_id_seccion'))
            <p class="text-danger">{{$errors->first('seccion_id_seccion')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="fecha">Fecha</label>
                        <input class="form-control Date"  type="date"  name="fecha" id="fecha" value="{{old('fecha')}}"                         required="required"
                        >
                        @if($errors->has('fecha'))
            <p class="text-danger">{{$errors->first('fecha')}}</p>
            @endif
        </div>
                        <div>
            <button class="btn btn-primary" type="submit">Create</button>
            <a href="{{ url()->previous() }}">Back</a>
        </div>
        </form>
        </div>
    </div>
</div>
@endsection

resources/views/inscripcions/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="card">

        <div class="card-header">
            <h1> Inscripcion Edit </h1>
        </div>
        <div class="card-body">

    @if($errors->any())
    <ul>
        @foreach($errors->all() as $error)
        <li class="text-danger">{{ $error }}</li>
        @endforeach
    </ul>

    @endif

    <form action="{{route('inscripcions.update',['inscripcion'=>$inscripcion->id])}}" method="POST" novalidate>
        @csrf
        @method('PUT')
        

                        <div class="form-group">
            <label for="id_inscripcion">Id Inscripcion</label>
                    <input class="form-control Integer"  type="number"  name="id_inscripcion" id="id_inscripcion" value="{{old('id_inscripcion',$inscripcion->id_inscripcion)}}"
                                    required="required"
                        >
                    @if($errors->has('id_inscripcion'))
            <p class="text-danger">{{$errors->first('id_inscripcion')}}</p>
            @endif
        </div>
                                                <div class="form-group">
            <label for="alumno_id_alumno">Alumno Id Alumno</label>
                    <input class="form-control Integer"  type="number"  name="alumno_id_alumno" id="alumno_id_alumno" value="{{old('alumno_id_alumno',$inscripcion->alumno_id_alumno)}}"
                                    required="required"
                        >
                    @if($errors->has('alumno_id_alumno'))
            <p class="text-danger">{{$errors->first('alumno_id_alumno')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="seccion_id_seccion">Seccion Id Seccion</label>
                    <input class="form-control Integer"  type="number"  name="seccion_id_seccion" id="seccion_id_seccion" value="{{old('seccion_id_seccion',$inscripcion->seccion_id_seccion)}}"
                                    required="required"
                        >
                    @if($errors->has('seccion_id_seccion'))
            <p class="text-danger">{{$errors->first('seccion_id_seccion')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="fecha">Fecha</label>
                    <input class="form-control Date"  type="date"  name="fecha" id="fecha" value="{{old('fecha',$inscripcion->fecha)}}"
                                    required="required"
                        >
                    @if($errors->has('fecha'))
            <p class="text-danger">{{$errors->first('fecha')}}</p>
            @endif
        </div>
                        <div>
            <button class="btn btn-primary" type="submit">Save</button>
            <a href="{{ url()->previous() }}">Back</a>
        </div>
    </form>
    </div>
        </div>

</div>
@endsection

resources/views/inscripcions/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">

    @if(session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
    @endif
    <div class="card">
        <div class="card-header">
            <h1> Inscripcions </h1>
        </div>
    <div class="card-body">

    <div>
        <a href="{{route('inscripcions.create')}}">New</a>
    </div>
    <table class="table table-striped">
        @if(count($inscripcions))
        <thead>
            <tr>
                <th>&nbsp;</th>
                                                <td>Id Inscripcion</td>
                
                                
                                                <td>Alumno Id Alumno</td>
                
                                                <td>Seccion Id Seccion</td>
                
                                                <td>Fecha</td>
                
                            </tr>

        </thead>
        @endif
        <tbody>
            @forelse($inscripcions as $inscripcion)
            <tr>
                <td>
                    <a href="{{route('inscripcions.show',['inscripcion'=>$inscripcion] )}}">Show</a>
                    <a href="{{route('inscripcions.edit',['inscripcion'=>$inscripcion] )}}">Edit</a>
                    <a href="javascript:void(0)" onclick="event.preventDefault();
                    document.getElementById('delete-inscripcion-{{$inscripcion->id}}').submit();">
                        Delete
                    </a>
                    <form id="delete-inscripcion-{{$inscripcion->id}}" action="{{route('inscripcions.destroy',['inscripcion'=>$inscripcion])}}" method="POST" style="display: none;">
                        @csrf
                        @method('DELETE')
                    </form>
                </td>
                                                <td>{{$inscripcion->id_inscripcion}}</td>
                                                                                                <td>{{$inscripcion->alumno_id_alumno}}</td>
                                                                <td>{{$inscripcion->seccion_id_seccion}}</td>
                                                                <td>{{$inscripcion->fecha}}</td>
                                
            </tr>
            @empty
            <p>No Inscripcions</p>
            @endforelse
        </tbody>
    </table>
    </div>
    </div>

</div>

@endsection

resources/views/inscripcions/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">

    <div class="card mb-4">

        <div class="card-header">
            <h1> Inscripcion Show </h1>
        </div>

    <div class="card-body">
                        <div class="form-group">
            <label class="col-form-label" for="value">Id Inscripcion</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$inscripcion->id_inscripcion}}">
        </div>
                                                <div class="form-group">
            <label class="col-form-label" for="value">Alumno Id Alumno</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$inscripcion->alumno_id_alumno}}">
        </div>
                                <div class="form-group">
            <label class="col-form-label" for="value">Seccion Id Seccion</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$inscripcion->seccion_id_seccion}}">
        </div>
                                <div class="form-group">
            <label class="col-form-label" for="value">Fecha</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$inscripcion->fecha}}">
        </div>
                    </div>

    </div>

    <div class="card mb-4">

        
    </div>



    <a href="{{ url()->previous() }}">Back</a>
</div>
@endsection