routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::resource('alumnos', 'AlumnoController');

Route::resource('catedraticos', 'CatedraticoController');
Route::resource('contratos', 'ContratoController');
Route::resource('grados', 'GradoController');
Route::resource('inscripcions', 'InscripcionController');
Route::resource('notas', 'NotaController');
Route::resource('seccions', 'SeccionController');
Route::resource('sucursals', 'SucursalController');

app/Http/Controllers/API/CatedraticoController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use App\Http\Requests\CatedraticoPostRequest;
use App\Http\Controllers\Controller;
use App\Http\Models\Catedratico\Catedratico;

class CatedraticoController extends Controller
{


    public function index()
    {
        return Catedratico::all();
    }

    public function show(Request $request, Catedratico $catedratico)
    {
        return $catedratico;
    }

    public function store(CatedraticoPostRequest $request)
    {
        $data = $request->validated();
        $catedratico = Catedratico::create($data);
        return $catedratico;
    }

    public function update(CatedraticoPostRequest $request, Catedratico $catedratico)
    {
        $data = $request->validated();
        $catedratico->fill($data);
        $catedratico->save();

        return $catedratico;
    }

    public function destroy(Request $request, Catedratico $catedratico)
    {
        $catedratico->delete();
        return $catedratico;
    }

}

app/Http/Controllers/CatedraticoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\CatedraticoPostRequest;
use App\Http\Models\Catedratico\Catedratico;


class CatedraticoController extends Controller
{

    public function index()
    {
        $catedraticos = Catedratico::all();
        return view('catedraticos.index', compact('catedraticos'));
    }

    public function show(Request $request, Catedratico $catedratico)
    {
        return view('catedraticos.show', compact('catedratico'));
    }

    public function create()
    {
        return view('catedraticos.create');
    }

    public function store(CatedraticoPostRequest $request)
    {
        $data = $request->validated();
        $catedratico = Catedratico::create($data);
        return redirect()->route('catedraticos.index')->with('status', 'Catedratico created!');
    }

    public function edit(Request $request, Catedratico $catedratico)
    {
        return view('catedraticos.edit', compact('catedratico'));
    }

    public function update(CatedraticoPostRequest $request, Catedratico $catedratico)
    {
        $data = $request->validated();
        $catedratico->fill($data);
        $catedratico->save();
        return redirect()->route('catedraticos.index')->with('status', 'Catedratico updated!');
    }

    public function destroy(Request $request, Catedratico $catedratico)
    {
        $catedratico->delete();
        return redirect()->route('catedraticos.index')->with('status', 'Catedratico destroyed!');
    }
}

resources/views/catedraticos/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="card">

        <div class="card-header">
            <h1> Catedratico Create </h1>
        </div>
        <div class="card-body">

        @if($errors->any())
        <ul>
            @foreach($errors->all() as $error)
            <li class="text-danger">{{ $error }}</li>
            @endforeach
        </ul @endif <form action="{{route('catedraticos.store')}}" method="POST" novalidate>
        @csrf
        
                        <div class="form-group">
            <label for="id_catedratico">Id Catedratico</label>
                        <input class="form-control Integer"  type="number"  name="id_catedratico" id="id_catedratico" value="{{old('id_catedratico')}}"                         required="required"
                        >
                        @if($errors->has('id_catedratico'))
            <p class="text-danger">{{$errors->first('id_catedratico')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="nombre">Nombre</label>
                        <input class="form-control String"  type="text"  name="nombre" id="nombre" value="{{old('nombre')}}"             maxlength="50"
                                    required="required"
                        >
                        @if($errors->has('nombre'))
            <p class="text-danger">{{$errors->first('nombre')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="apellido">Apellido</label>
                        <input class="form-control String"  type="text"  name="apellido" id="apellido" value="{{old('apellido')}}"             maxlength="50"
                                    required="required"
                        >
                        @if($errors->has('apellido'))
            <p class="text-danger">{{$errors->first('apellido')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="dpi">Dpi</label>
                        <input class="form-control String"  type="text"  name="dpi" id="dpi" value="{{old('dpi')}}"             maxlength="13"
                                    required="required"
                        >
                        @if($errors->has('dpi'))
            <p class="text-danger">{{$errors->first('dpi')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="telefono">Telefono</label>
                        <input class="form-control String"  type="text"  name="telefono" id="telefono" value="{{old('telefono')}}"             maxlength="10"
                                    required="required"
                        >
                        @if($errors->has('telefono'))
            <p class="text-danger">{{$errors->first('telefono')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="correo">Correo</label>
                        <input class="form-control String"  type="text"  name="correo" id="correo" value="{{old('correo')}}"             maxlength="125"
                                    required="required"
                        >
                        @if($errors->has('correo'))
            <p class="text-danger">{{$errors->first('correo')}}</p>
            @endif
        </div>
                        <div>
            <button class="btn btn-primary" type="submit">Create</button>
            <a href="{{ url()->previous() }}">Back</a>
        </div>
        </form>
        </div>
    </div>
</div>
@endsection

resources/views/catedraticos/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="card">

        <div class="card-header">
            <h1> Catedratico Edit </h1>
        </div>
        <div class="card-body">

    @if($errors->any())
    <ul>
        @foreach($errors->all() as $error)
        <li class="text-danger">{{ $error }}</li>
        @endforeach
    </ul>

    @endif

    <form action="{{route('catedraticos.update',['catedratico'=>$catedratico->id])}}" method="POST" novalidate>
        @csrf
        @method('PUT')
        

                        <div class="form-group">
            <label for="id_catedratico">Id Catedratico</label>
                    <input class="form-control Integer"  type="number"  name="id_catedratico" id="id_catedratico" value="{{old('id_catedratico',$catedratico->id_catedratico)}}"
                                    required="required"
                        >
                    @if($errors->has('id_catedratico'))
            <p class="text-danger">{{$errors->first('id_catedratico')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="nombre">Nombre</label>
                    <input class="form-control String"  type="text"  name="nombre" id="nombre" value="{{old('nombre',$catedratico->nombre)}}"
                                    required="required"
                        >
                    @if($errors->has('nombre'))
            <p class="text-danger">{{$errors->first('nombre')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="apellido">Apellido</label>
                    <input class="form-control String"  type="text"  name="apellido" id="apellido" value="{{old('apellido',$catedratico->apellido)}}"
                                    required="required"
                        >
                    @if($errors->has('apellido'))
            <p class="text-danger">{{$errors->first('apellido')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="dpi">Dpi</label>
                    <input class="form-control String"  type="text"  name="dpi" id="dpi" value="{{old('dpi',$catedratico->dpi)}}"
                                    required="required"
                        >
                    @if($errors->has('dpi'))
            <p class="text-danger">{{$errors->first('dpi')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="telefono">Telefono</label>
                    <input class="form-control String"  type="text"  name="telefono" id="telefono" value="{{old('telefono',$catedratico->telefono)}}"
                                    required="required"
                        >
                    @if($errors->has('telefono'))
            <p class="text-danger">{{$errors->first('telefono')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="correo">Correo</label>
                    <input class="form-control String"  type="text"  name="correo" id="correo" value="{{old('correo',$catedratico->correo)}}"
                                    required="required"
                        >
                    @if($errors->has('correo'))
            <p class="text-danger">{{$errors->first('correo')}}</p>
            @endif
        </div>
                        <div>
            <button class="btn btn-primary" type="submit">Save</button>
            <a href="{{ url()->previous() }}">Back</a>
        </div>
    </form>
    </div>
        </div>

</div>
@endsection

resources/views/catedraticos/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">

    @if(session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
    @endif
    <div class="card">
        <div class="card-header">
            <h1> Catedraticos </h1>
        </div>
    <div class="card-body">

    <div>
        <a href="{{route('catedraticos.create')}}">New</a>
    </div>
    <table class="table table-striped">
        @if(count($catedraticos))
        <thead>
            <tr>
                <th>&nbsp;</th>
                                                <td>Id Catedratico</td>
                
                                                <td>Nombre</td>
                
                                                <td>Apellido</td>
                
                                                <td>Dpi</td>
                
                                                <td>Telefono</td>
                
                                                <td>Correo</td>
                
                            </tr>

        </thead>
        @endif
        <tbody>
            @forelse($catedraticos as $catedratico)
            <tr>
                <td>
                    <a href="{{route('catedraticos.show',['catedratico'=>$catedratico] )}}">Show</a>
                    <a href="{{route('catedraticos.edit',['catedratico'=>$catedratico] )}}">Edit</a>
                    <a href="javascript:void(0)" onclick="event.preventDefault();
                    document.getElementById('delete-catedratico-{{$catedratico->id}}').submit();">
                        Delete
                    </a>
                    <form id="delete-catedratico-{{$catedratico->id}}" action="{{route('catedraticos.destroy',['catedratico'=>$catedratico])}}" method="POST" style="display: none;">
                        @csrf
                        @method('DELETE')
                    </form>
                </td>
                                                <td>{{$catedratico->id_catedratico}}</td>
                                                                <td>{{$catedratico->nombre}}</td>
                                                                <td>{{$catedratico->apellido}}</td>
                                                                <td>{{$catedratico->dpi}}</td>
                                                                <td>{{$catedratico->telefono}}</td>
                                                                <td>{{$catedratico->correo}}</td>
                                
            </tr>
            @empty
            <p>No Catedraticos</p>
            @endforelse
        </tbody>
    </table>
    </div>
    </div>

</div>

@endsection

resources/views/catedraticos/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">

    <div class="card mb-4">

        <div class="card-header">
            <h1> Catedratico Show </h1>
        </div>

    <div class="card-body">
                        <div class="form-group">
            <label class="col-form-label" for="value">Id Catedratico</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$catedratico->id_catedratico}}">
        </div>
                                <div class="form-group">
            <label class="col-form-label" for="value">Nombre</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$catedratico->nombre}}">
        </div>
                                <div class="form-group">
            <label class="col-form-label" for="value">Apellido</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$catedratico->apellido}}">
        </div>
                                <div class="form-group">
            <label class="col-form-label" for="value">Dpi</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$catedratico->dpi}}">
        </div>
                                <div class="form-group">
            <label class="col-form-label" for="value">Telefono</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$catedratico->telefono}}">
        </div>
                                <div class="form-group">
            <label class="col-form-label" for="value">Correo</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$catedratico->correo}}">
        </div>
                    </div>

    </div>

    <div class="card mb-4">

        
    </div>



    <a href="{{ url()->previous() }}">Back</a>
</div>
@endsection